//! Chatbot module - relays Telegram messages to Claude Code.

pub mod bot_messages;
pub mod callbacks;
pub mod claude_code;
pub mod cognitive;
pub mod context;
pub mod database;
pub mod debounce;
pub mod document;
pub mod dual_lane;
pub mod engine;
pub mod event_bus;
pub mod format;
pub mod gemini;
pub mod health;
pub mod journal;
pub mod message;
pub mod metrics;
pub mod planner;
pub mod prompt_builder;
pub mod reflection;
pub mod reminders;
pub mod self_eval;
pub mod snapshot;
pub mod telegram;
pub mod tool_dispatch;
pub mod tool_registry;
pub mod tools;
pub mod tts;
pub mod verify;
pub mod whisper;
pub mod workflow;
pub mod yandex;

pub use claude_code::ClaudeCode;
pub use engine::{ChatbotConfig, ChatbotEngine};
pub use message::{ChatMessage, ReplyTo};
pub use prompt_builder::system_prompt;
pub use telegram::TelegramClient;
pub use whisper::{GroqTranscriber, OpenAITranscriber, Whisper};
